---
Name: "cluster-initialize"
Description: "Initialize v4.6 Cluster: Shared Profile & Elect Leader"
Documentation: |
  For the v4.6 Cluster Pattern

  Creates the Cluster for Digital Rebar

    1. will create shared profile if missing (named after cluster manager machine)
    1. identified machine running this task as the cluster manager
    1. will add cluster machines to the shared profile based on cluster/filter
    1. will make machine leader(s) if no leader is present

  Note: your cluster/filter must apply to >0 machines!

  For operational guidelines, see :ref:`rs_cluster_pattern`
ExtraClaims:
  - scope: "profiles"
    action: "*"
    specific: "*"
  - scope: "machines"
    action: "*"
    specific: "*"
RequiredParams:
  - cluster/filter
  - cluster/leader-count
OptionalParams:
  - cluster/profile
Meta:
  type: "install"
  icon: "object group outline"
  color: "brown"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
  copyright: "RackN 2020"
Templates:
- Contents: |-
    #!/usr/bin/env bash
    # Create Cluster Profile & Elect Leader
    set -e

    echo "Starting: Setup Cluster"

    # Get access and who we are.
    {{template "setup.tmpl" .}}

    drpcli machines set $RS_UUID param cluster/manager to true > /dev/null

    {{ if and (.ParamExists "cluster/profile") (not (eq "cluster-v43" (.Param "cluster/profile"))) }}

    CLUSTER_PROFILE={{.Param "cluster/profile"}}
    echo "--- SKIPPING: CLUSTER PROFILE SETUP ---"

    {{ else }}

    CLUSTER_PROFILE={{ .Machine.Name }}
    echo "--- START: CLUSTER PROFILE SETUP ---"
    if drpcli profiles exists "{{ .Machine.Name }}" ; then
      echo "  Profile {{ .Machine.Name }} Already Exists"
    else
      drpcli profiles create '{"Name":"{{ .Machine.Name }}",
        "Description": "Cluster Tracking (added automatically)",
        "Params":{"cluster/profile":"{{ .Machine.Name }}"},
        "Meta":{"icon":"object group outline", "color": "green"},
      }' > /dev/null
      echo "  Created Profile {{ .Machine.Name }}"
    fi

    if [[ $(drpcli machines count Uuid=$RS_UUID Profile={{.Machine.Name}}) -eq 0 ]]; then
      drpcli machines addprofile $RS_UUID {{ .Machine.Name }} > /dev/null
      echo "  Added Profile {{ .Machine.Name }} to Machine {{ .Machine.Name }}"
    else
      echo "  Already Exists: Profile {{ .Machine.Name }} on Machine $RS_UUID"
    fi
    echo "--- CLUSTER PROFILE SETUP ---"

    {{ end }}

    echo "Collecting machines as per cluster/filter: {{ .Param "cluster/filter" }}"
    CLUSTER_MACHINES="$(drpcli machines list Uuid Ne $RS_UUID {{.Param "cluster/filter"}} --slim Params,Meta)"

    if [[ $(jq length <<< "$CLUSTER_MACHINES") -lt 1 ]]; then
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      echo "FIX REQUIRED: no members match for {{.Param "cluster/filter"}}"
      echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      exit 1
    fi

    CLUSTER_UUIDS=$(jq -r ".[].Uuid" <<< "$CLUSTER_MACHINES")
    NUM_LEADERS=$(drpcli machines count cluster/leader Eq true Uuid Ne $RS_UUID {{.Param "cluster/filter"}})
    TARGET_LEADERS={{.Param "cluster/leader-count"}}

    echo "--- Initializing Machines in Cluster: elect leaders & add $CLUSTER_PROFILE profile ---"
    for uuid in $CLUSTER_UUIDS; do
      if drpcli machines addprofile $uuid $CLUSTER_PROFILE > /dev/null; then
        echo "  added $CLUSTER_PROFILE to $uuid"
      else
        echo "  no action: $CLUSTER_PROFILE was already on $uuid"
      fi
      if [[ $NUM_LEADERS -lt $TARGET_LEADERS ]]; then
        if [[ "$(drpcli machines get $uuid param cluster/leader)" != "true" ]]; then
          echo "  Appointed $uuid as leader ($NUM_LEADERS of $TARGET_LEADERS)"
          drpcli machines set $uuid param cluster/leader to true  > /dev/null
          NUM_LEADERS=$((NUM_LEADERS+1))
        else
          echo "  Skip: $uuid is already a leader"
        fi
      else
        echo "  We have enough leaders ($NUM_LEADERS of $TARGET_LEADERS)"
      fi
    done
    echo "--- Initialization done ---"

    echo "Complete: Setup Cluster"
    exit 0
  Name: cluster-initialize
