---
Name: "elasticsearch-setup"
Description: "A task to install and setup elasticsearch"
Documentation: |
  A task to install and setup elasticsearch.  This is a very simple single instance.
Templates:
  - Name: "install-elasticsearch.sh"
    Contents: |
      #!/bin/bash

      {{ template "setup.tmpl" . }}

      if [[ "$OS_FAMILY" == "rhel" ]] ; then
        curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-x86_64.rpm
        rpm -e elasticsearch || :
        rpm --install elasticsearch-7.9.2-x86_64.rpm
        rm -f elasticsearch-7.9.2-x86_64.rpm
      elif [[ "$OS_FAMILY" == "debian" ]] ; then
        curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-amd64.deb
        dpkg -r elasticsearch || :
        dpkg -i elasticsearch-7.9.2-amd64.deb
        rm -f elasticsearch-7.9.2-amd64.deb
      else
        echo "Unknown install method for $OS_FAMILY"
        exit 1
      fi
      exit 0
  - Name: "start-elasticsearch.sh"
    Contents: |
      service enable elasticsearch
      service restart elasticsearch

Meta:
  icon: "bug"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"