---
Name: "elasticsearch-setup"
Description: "A task to install and setup elasticsearch"
Documentation: |
  A task to install and setup elasticsearch.  This is a very simple single instance.
Templates:
  - Name: "install-elasticsearch.sh"
    Contents: |
      #!/bin/bash

      {{ template "setup.tmpl" . }}

      if [[ "$OS_FAMILY" == "rhel" ]] ; then
        rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

        REPODIR=/etc/yum.repos.d/
        if [[ -e /etc/zypp/repos.d ]] ; then
          REPODIR=/etc/zypp/repos.d
        fi

        cat > $REPODIR/elastic.repo <<EOF
      [elastic-7.x]
      name=Elasticsearch repository for 7.x packages
      baseurl=https://artifacts.elastic.co/packages/7.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
      EOF

        if which zypper 2>/dev/null ; then
          zypper install -y elasticsearch
        elif which dnf 2>/dev/null ; then
          dnf install -y elasticsearch
        else
          yum install -y elasticsearch
        fi
      elif [[ "$OS_FAMILY" == "debian" ]] ; then
        wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        apt-get install -y apt-transport-https
        echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-7.x.list
        apt-get update && apt-get install -y elasticsearch
      else
        echo "Unknown install method for $OS_FAMILY"
        exit 1
      fi
      exit 0
  - Name: "start-elasticsearch.sh"
    Contents: |
      #!/bin/bash

      /bin/systemctl daemon-reload
      service elasticsearch enable
      service elasticsearch restart

Meta:
  icon: "bug"
  color: "green"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
