---
Description: "A task to open ports in Firewall"
Documentation: |
  Requires that ``firewall-cmd`` or ``ufs`` to be enabled system.

  Will reset the firewall at the end of the task.

Name: "network-firewall"
RequiredParams:
  - network/firewall-ports
Templates:
- Contents: |-
    #!/bin/bash
    # update firewall rules

    set -e

    {{ if empty (.Param "network/firewall-ports") }}
      echo "No Action: No Firewall Ports defined in network/firewall-ports."
    {{ else }}

    {{template "setup.tmpl" .}}

    case $osfamily in
      redhat|centos|amzn) yum install -y firewalld ;;
      debian|ubuntu) sudo apt install -y ufw ;;
      *) >&2 echo "Unsupported package manager family '$osfamily'."
         exit 1 ;;
    esac

    # just in case, try starting firewalld
    if systemctl status firewalld | grep Loaded ; then

      {{range $index, $port := .Param "network/firewall-ports" }}
        {{ if contains "/" $port }}
        PORT={{$port}}
        {{ else }}
        PORT={{$port}}/tcp
        {{ end }}
        echo "Rule {{$index}}: add-port $PORT"
        case $osfamily in
          redhat|centos) firewall-cmd --permanent --add-port=$PORT ;;
          debian|ubuntu) sudo ufw allow $PORT ;;
        esac
      {{else}}
        echo "No network/firewall-ports defined"
      {{end}}

      echo "restart firewall"
      case $osfamily in
        redhat|centos) firewall-cmd --reload ;;
        debian|ubuntu) sudo ufw reload ;;
      esac
    
      {{ end }}
    else
      echo "WARNING: no firewalld found, skipping network config"
    fi

    echo "done"

  Name: firewall-ports
Meta:
  icon: "fire"
  color: "blue"
  title: "RackN Content Copyright 2020"
  feature-flags: "sane-exit-codes"
