---
Description: "A task to open ports in Firewalld"
Documentation: |
  Requires that firewall-cmd enabled system
  Will reset the firewall at the end of the task
Name: "network-firewalld"
RequiredParams:
  - network/firewalld-ports
Templates:
- Contents: |-
    #!/bin/bash
    # update firewall rules

    set -e

    {{template "setup.tmpl" .}}

    echo "Looking for firewall-cmd: [$(which firewall-cmd)]"
    if which firewall-cmd >/dev/null 2>/dev/null ; then
      echo "Found firewall-cmd, adding ports"
    else
      echo "firewalld not installed on system, installing..."
      yum install -y firewalld
    fi

    {{range $index, $port := .Param "network/firewalld-ports" }}
      {{ if contains "/" $port }}
      PORT={{$port}}
      {{ else }}
      PORT={{$port}}/tcp
      {{ end }}
      echo "Rule {{$index}}: add-port $PORT"
      firewall-cmd --permanent --add-port=$PORT
    {{else}}
      echo "No network/firewalld-ports defined"
    {{end}}

    echo "restart firewall"
    firewall-cmd --reload

    echo "done"

  Name: firewalld-ports
Meta:
  icon: "fire"
  color: "blue"
  title: "RackN Content Copyright 2019"
  feature-flags: "sane-exit-codes"
