FROM alpine:latest
ENV DRPCLI_VER="v4.2.0-beta3.0%2Bg71eb5cb0dd4a2cc2347de53beb383c448636cc91"
#ADD https://rebar-catalog.s3-us-west-2.amazonaws.com/drpcli/${DRPCLI_VER}/arm64/linux/drpcli /usr/bin/
RUN apk add --update curl bash
COPY drpcli /usr/bin/drpcli
RUN chmod 755 /usr/bin/drpcli
RUN ln -s /usr/bin/drpcli /usr/bin/jq
ENTRYPOINT /usr/bin/drpcli machines processjobs
