FROM alpine:latest
MAINTAINER eng@rackn.com

RUN echo "===> Adding Python runtime..."                                       && \
    apk --no-cache --update add openssh-client python3 openssl ca-certificates && \
    apk --no-cache --update add --virtual build-dependencies py3-pip py3-wheel    \
        python3-dev libffi-dev openssl-dev build-base

RUN echo "===> Upgrading PIP and CFFI packages..." && \
    pip3 install --upgrade pip cffi

RUN echo "===> Installing Ansible..."     && \
    pip3 install ansible==2.9.1

RUN echo "===> Installing PyVMOMI..."     && \
    pip3 install --no-cache-dir pyvmomi

RUN echo "===> Installing yq..."          && \
    pip3 install --no-cache-dir --upgrade yq

RUN echo "===> Installing tools..."       && \
    apk --no-cache --update add \
        bash \
        vim \
        binutils \
        coreutils \
        sed \
        gawk \
        py-dnspython \
        py-boto \
        py-netaddr \
        bind-tools \
        html2text \
        git \
        curl \
        wget \
        openssh-client \
        openssh-keygen

RUN echo "===> Instal Ansible Galaxy Communitis VMWARE..." && \
    ansible-galaxy collection install community.vmware

### REALLY weird - had to install twice, to get python and pyvmomi
###        environment setup correctly for ansible to "see" it
RUN echo "===> Installing PyVMOMI..."     && \
    apk add py3-pip                       && \
    pip3 install --no-cache-dir pyvmomi

RUN echo "===> Cleaning up..."            && \
    apk del build-dependencies            && \
    rm -rf /var/cache/apk/*

RUN curl -o drpcli440 https://s3-us-west-2.amazonaws.com/rebar-catalog/drpcli/v4.4.0/amd64/linux/drpcli && \
    chmod 755 drpcli440                                                                                 && \
    ./drpcli440 catalog item download drpcli to /usr/bin/drpcli                                         && \
    chmod 755 /usr/bin/drpcli                                                                           && \
    rm drpcli440                                                                                        && \
    ln -s /usr/bin/drpcli /usr/bin/jq                                                                   && \
    ln -s /usr/bin/drpcli /usr/bin/drpjq                                                                && \
    echo "Installed DRPCLI $(drpcli version)"
ENTRYPOINT /usr/bin/drpcli machines processjobs
