FROM bitnami/minideb:buster
MAINTAINER "The RackN Team <support@rackn.com>"

# Alpine musl libc does NOT work with OVFTool - so the switch to minideb:buster

#    add-apt-repository ppa:ansible/ubuntu                     && \

RUN install_packages gnupg

RUN echo "===> Setting up environment..."                     && \
    install_packages apt-utils software-properties-common        \
    python3-software-properties                               && \
    echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main" > /etc/apt/sources.list.d/ansible.list  && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367  && \
    apt -y update                                             && \
    install_packages ansible                                  && \
    install_packages                                             \
        bash vim git curl wget dnsutils html2text                \
        openssh-client python3 openssl ca-certificates           \
        python3-pip python3-wheel libffi-dev libssl-dev          \
        python3-dnspython python3-boto python3-netaddr           \
        python3-setuptools gnupg                              && \
    python3 -m pip install --upgrade pip cffi                 && \
    python3 -m pip install --no-cache-dir pyvmomi             && \
    python3 -m pip install --no-cache-dir --upgrade yq

RUN echo "===> Install Ansible Galaxy Communities VMware..."  && \
    curl -fsSL -o community.vmware.tar.gz https://s3-us-west-2.amazonaws.com/get.rebar.digital/artifacts/vmtools/community-vmware-1.2.1-dev8.tar.gz  && \
    ansible-galaxy collection install ./community.vmware.tar.gz && \
    rm -f community.vmware.tar.gz

### REALLY weird - had to install twice, to get python and pyvmomi
###        environment setup correctly for ansible to "see" it
RUN echo "===> Installing PyVMOMI..."                       && \
    install_packages python3-pip                            && \
    python3 -m pip install --no-cache-dir pyvmomi

RUN echo "===> Fixing python 2/3 problems for ansible..."   && \
    echo "localhost ansible_python_interpreter=/usr/bin/python3" >> /etc/ansible/hosts

RUN curl -fsSL -o ovftool.bundle https://s3-us-west-2.amazonaws.com/get.rebar.digital/artifacts/vmtools/VMware-ovftool-4.4.0-15722219-lin.x86_64.bundle  && \
    chmod +x ovftool.bundle && \
    ./ovftool.bundle --eulas-agreed --required --console && \
    rm -f ovftool.bundle

RUN curl -o drpcli440 https://s3-us-west-2.amazonaws.com/rebar-catalog/drpcli/v4.4.0/amd64/linux/drpcli && \
    chmod 755 drpcli440                                                                                 && \
    ./drpcli440 catalog item download drpcli to /usr/bin/drpcli                                         && \
    chmod 755 /usr/bin/drpcli                                                                           && \
    rm drpcli440                                                                                        && \
    ln -s /usr/bin/drpcli /usr/bin/jq                                                                   && \
    ln -s /usr/bin/drpcli /usr/bin/drpjq                                                                && \
    echo "Installed DRPCLI $(drpcli version)"
ENTRYPOINT /usr/bin/drpcli machines processjobs
