FROM alpine:latest
RUN apk update
RUN apk upgrade

MAINTAINER "The RackN Team <support@rackn.com>"

ENV GOVC_VER="v0.23.0"
ENV GOVC_SHA256="6de2afb3276b950ded9b6bd59ec6b0c57e43a4acdbb0450783d7c9ea85dd7ca4"
ENV DRPCLI_VER="v4.3.3"
ENV DRPCLI_SHA256="e42fe87000639b66803588889ddee8cbb79449e55b365f6f80a651b112d7d674"

RUN apk add --no-cache bash bind-tools

ADD https://github.com/vmware/govmomi/releases/download/${GOVC_VER}/govc_linux_amd64.gz ./
RUN gunzip govc_linux_amd64.gz
RUN mv govc_linux_amd64 /usr/bin/govc
RUN chmod 755 /usr/bin/govc
RUN rm -f govc_linux_amd64.gz

ADD https://rebar-catalog.s3-us-west-2.amazonaws.com/drpcli/${DRPCLI_VER}/amd64/linux/drpcli /usr/bin/
RUN chmod 755 /usr/bin/drpcli
RUN ln -s /usr/bin/drpcli /usr/bin/jq
ENTRYPOINT /usr/bin/drpcli machines processjobs
