FROM alpine:latest
#RUN apk update
#RUN apk upgrade
#RUN apk add bash

MAINTAINER "The RackN Team <support@rackn.com>"

ENV GOVC_VER="v0.22.1"
ENV GOVC_SHA="0579871b00a2112fb7c5d1a92a4cefe1322bd74e"
ENV DRPCLI_VER="v4.3.0-beta13.4%2Bg7112569c3d75b3e5d6261070ec4085078c1273d5"

RUN apk add --no-cache bash

ADD https://github.com/vmware/govmomi/releases/download/${GOVC_VER}/govc_linux_amd64.gz ./
RUN gunzip govc_linux_amd64.gz
RUN mv govc_linux_amd64 /usr/bin/govc
RUN chmod 755 /usr/bin/govc
RUN rm -f govc_linux_amd64.gz

ADD https://rebar-catalog.s3-us-west-2.amazonaws.com/drpcli/${DRPCLI_VER}/amd64/linux/drpcli /usr/bin/
#COPY drpcli /usr/bin/drpcli
RUN chmod 755 /usr/bin/drpcli
RUN ln -s /usr/bin/drpcli /usr/bin/jq
ENTRYPOINT /usr/bin/drpcli machines processjobs
