---
Name: "network-manage-routes"
Description: "Stage to set additional routes based on 'network-data' values. (Linux/ESXi/Darwin)"
Documentation: |
  This stage uses the ``network-data`` structure to set or remove any routes specified
  based on the reference tag named in ``network-data-tag`` Param setting.

  The action of add or remove is controlled by the Param ``network-manage-routes-command``, which
  defaults to adding routes to a system.

  An example of ``network-data`` Param values known to work with this Stage are as follows
  (the Param ``network-data-tag`` would be set to ``myroutes`` in this example):

  in YAML format:
    ::

      network-data:
        myroutes:
          routes:
          - gateway: 192.168.100.1
            netmask: 255.255.255.0
            network: 10.10.10.0
          - gateway: 172.17.92.254
            netmask: 255.255.255.0
            network: 10.20.20.0

  in JSON Format:

    ::

      {
        "myroutes": {
          "routes": [
            { "gateway": "192.168.100.1", "netmask": "255.255.255.0", "network": "10.10.10.0" },
            { "gateway": "172.17.92.254", "netmask": "255.255.255.0", "network": "10.20.20.0" }
          ]
        }
      }

  .. note:: The ``network-data`` structure is used for other network plumbing purposes too.  This
            example only shows valid syntax for adding routes.  Additional stanzas are likely to
            appear in a valid data structure.  See the documentation on the Param for more details.

Meta:
  color: "blue"
  icon: "list alternate outline"
  title: "RackN Content"
RequiredParams:
  - network-data
  - network-data-tag
OptionalParams:
  - network-manage-routes-command
Tasks:
  - network-manage-routes
