---
Name: "install-node-exporter"
Description: "A task to Install Node Exporter for Prometheus"
Documentation: |
  This task installs the Node Exporter package on a given machine.
  It also will record the Node Exporter systems IP address in the
  param 'drp-prom-mon/node-exporter'.  This value will subsequently
  be used by the Prometheus Stage to collect (scrape) metrics from
  this machine.

  The Param 'drp-prom-mon/cluster-profile' MUST BE SET on the machine
  so that the Stage can record the Pram information correctly.

  If the Param 'drp-prom-mon/cluster-profile' is set to the value

    prom-mon-single-node

  Then the Stage will assume this is an all-in-one DRP/Prometheus/
  Node Exporter/Grafana platform - and you DO NOT have to set the
  cluster profile.

Meta:
  color: "orange"
  feature-flags: "sane-exit-codes"
  icon: "dashboard"
  title: "install-node-exporter"

OptionalParams:
  - "drp-prom-mon/node-exporter"

Templates:
  - Contents: ""
    ID: "install-node-exporter.sh.tmpl"
    Name: "Install Node Exporter"
    Path: ""

ReadOnly: true
