Name: image-install-cloud-init
Description: Install cloud-init service on system to be imaged.
Documentation: |
  Simple task to add ``cloud-init`` pacakge to an Image Builder image
  which can be used by the ``image-deploy`` plugin to customize the installed
  Machine.

ReadOnly: true
Meta:
  color: purple
  feature-flags: sane-exit-codes
  icon: pin
  title: Image Builder suite
  origin: rackn/image-builder
Templates:
  - Contents: |
      #!/bin/bash
      # Image builder setup tasks
      # origin: rackn/image-builder
      {{template "setup.tmpl" .}}

      install cloud-init
    Name: image-install-cloud-init
    Path: ""
