Name: image-builder-stage
Description: A task to stage the Image Builder image to DRP.
Documentation: |
  Copies the built image to a remote HTTP file server location.  Currently the only supported
  HTTP file server is a DRP Endpoint, in the ``Files`` location.

ReadOnly: true
Meta:
  color: purple
  feature-flags: sane-exit-codes
  icon: pin
  title: Image Builder suite
  origin: rackn/image-builder
ExtraClaims:
  - scope: "files"
    action: "*"
    specific: "*"
Templates:
  - Contents: ''
    ID: "image-builder-stage.sh.tmpl"
    Name: image-builder-stage
    Path: ""
