Name: image-install-cloud-init
Description: Install cloud-init service on system to be imaged.
Documentation: |
  Simple task to add ``cloud-init`` pacakge to an Image Builder image
  which can be used by the ``image-deploy`` plugin to customize the installed
  Machine.

ReadOnly: true
Meta:
  color: purple
  feature-flags: sane-exit-codes
  icon: pin
  title: Image Builder suite
  origin: rackn/image-builder
Templates:
  - Contents: |
      #!/bin/bash
      # Image builder setup tasks
      # origin: rackn/image-builder
      {{template "setup.tmpl" .}}

      case $OS_FAMILY in
        debian)
          export DEBIAN_FRONTEND=noninteractive
          faketty () {
              script -qfce "$(printf "%q " "$@")"
          }
          if grep -q devpts /proc/mounts ; then
              faketty apt-get install -y cloud-init
          else
              mount -t devpts devpts /dev/pts
              faketty apt-get install -y cloud-init
              umount /dev/pts
          fi
          ;;
        rhel)
            install cloud-init
        ;;
      esac
      exit 0
    Name: image-install-cloud-init
    Path: ""
