---
Description: "Get the packer builder json and build scripts from git repo."
Name: "packer-builder-git-packer"
Documentation: |
  Performs a git checkout of the ``packer-builder/packer/`` directory in the
  ``digitalrebar/provision-content`` repo.

  The git repo directory will be checked out in the ``packer-builder/packer/``
  directory on the Machine this is run from.

Templates:
  - ID: "packer-builder-git-packer.sh.tmpl"
    Name: "packer-builder-git-packer"
Meta:
  icon: "cart arrow down"
  color: "blue"
  title: "RackN"
  feature-flags: "sane-exit-codes"
