---
Description: "A task to install and setup MetalLB"
Name: "krib-metallb"
Templates:
  - ID: "krib-metallb.sh.tmpl"
    Name: "Setup MetalLB"
    Path: ""
RequiredParams:
  - krib/cluster-profile
OptionalParams:
  - krib/metallb-config
  - metallb/monitoring-port
  - metallb/limits-cpu
  - metallb/limits-memory
  - metallb/l2-ip-range
  - metallb/l3-ip-range
  - metallb/l3-peer-address
Meta:
  icon: "sitemap"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
