---
Description: "A task to install Helm charts"
Name: "krib-helm-charts"
Documentation: |
  Installs Charts defined in helm/charts.
  This uses the Digital Rebar Cluster pattern so krib/cluster-profile must be set.
  The install checks to see if tiller is running and may skip initialization.
RequiredParams:
  - krib/cluster-profile
OptionalParams:
  - helm/charts
Templates:
  - ID: "krib-helm.sh.tmpl"
    Name: "Running Helm Charts on nodes"
    Path: ""
Meta:
  icon: "ship"
  color: "blue"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
