---
Name: "vault-config"
Description: "Configure a vault cluster."
RunnerWait: true
Tasks:
  - "vault-install"
  - "vault-config"
  - "vault-kms-plugin"
Meta:
  icon: "ship"
  color: "yellow"
  title: "Community Content"
