---
Name: lenovo-install-onecli
Description: "Install OneCli to manage Lenovo systems in-band"
Templates:
  - Name: "onecli-install"
    Contents: |
      #!/usr/bin/env bash
      {{ template "setup.tmpl" . }}
      {{ template "set-proxy-servers.sh.tmpl" .}}
      target="{{.Param "lenovo-onecli-install-target"}}"
      src="{{.ParamExpand "lenovo-onecli-url"}}"

      [[ -d $target ]] || mkdir -p "$target"
      [[ -x $target/OneCli ]] && exit 0
      curl -fgL "$src" -o onecli.tgz
      tar xzf onecli.tgz -C "$target"
      rm onecli.tgz
