---
Name: "redhat-subscription-unregister"
Description: "A task to unregister machine from Redhat Subscription Network"
Documentation: |
  A task to unregister machine from Redhat Subscription Network
Meta:
  icon: "key"
  color: "blue"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
Templates:
  - ID: "redhat-subscription-unregister.sh.tmpl"
    Name: "Unregister Redhat Subscription Network"
    Path: ""
