---
Name: "classify-stage-list-start"
Description: "Start a set of classification stages on a machine"
Documentation: |
  Using the parameter specified by the ``classify/stage-list-parameter``, the
  stages specified in that list will be added to the system.  This assumes that
  they are classify stages and have a single task of classify.
  No other tasks should preceed it on the stage, and the only other task that
  should follow is the ``classify-stage-list-stop`` task.

  Tasks will be dynamically injected in to the workflow after this task, if they
  have been specified by the appropriate control Params.

Meta:
  color: "blue"
  icon: "bug"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
Templates:
- Name: "classify-stage-list-start.sh"
  Meta:
    OS: "linux,darwin"
  Contents: |
    #!/usr/bin/env bash
    # Copyright RackN, 2020

    set -e

    {{ template "setup.tmpl" . }}

    {{ if eq (.ParamExists "classify/stage-list-parameter") false }}
    echo "classify/stage-list-parameter is not specified"
    exit 1
    {{ end }}

    {{ $lp := .Param "classify/stage-list-parameter" -}}
    {{ if eq (.ParamExists $lp) false -}}
    echo "classify/stage-list-parameter is {{$lp}} and it does not exist."
    exit 1
    {{ end -}}

    # Build new task list - This is dangerous and not to be done without planning.
    {{ $cid := add .Machine.CurrentTask 1 -}}
    {{ $first := slice .Machine.Tasks 0 $cid -}}
    {{ $seestop := 0 -}}
    {{ range $index, $taskname := (slice .Machine.Tasks $cid) -}}
       {{ if eq $taskname "classify-stage-list-stop" -}}
         {{ $seestop = $index -}}
       {{ end -}}
    {{ end -}}
    {{ $last := slice .Machine.Tasks (add $cid $seestop) -}}
    {{ range $index, $stagename := .ComposeParam $lp -}}
    {{ $first = append $first (printf "stage:%s" $stagename) -}}
    {{ $first = append $first "classify" -}}
    {{ end -}}
    {{ $full := concat $first $last -}}

    # Reset the task list
    drpcli machines update --force $RS_UUID - >/dev/null <<EOF
    Tasks: {{toJson $full}}
    EOF

    exit 0
- Name: "classify-stage-list-start.ps1"
  Meta:
    OS: "windows"
  Contents: |
    Write-Host "classify stage list start not supported on windows."
    exit 0
- Name: "classify-stage-list-start-esxi.sh"
  Meta:
    OS: "esxi"
  Contents: |
    #!/bin/sh
    echo "classify stage list start not supported on esxi."
    exit 0
