---
Name: "test-validation-success"
Description: "Example validation success task"
Documentation: |
  Example validation task that performs a "Success" validation.

Meta:
  color: "blue"
  icon: "bug"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
Templates:
- Name: "test_validation_success.sh"
  Contents: |
    #!/bin/bash
    # Copyright RackN, 2019

    set -e

    {{ template "setup.tmpl" . }}
    {{ template "validation-lib.tmpl" . }}

    # Will just exit with 0, and continue procssing further tasks.
    echo "($$): This is a successful validation task."

    validation_success

