---
Description: "A task to reboot to a workflow specifed by the edge-lab/reboot-workflow"
Name: "edge-lab-reboot-workflow"
Documentation: |
  A task to reboot to a workflow specifed by the edge-lab/reboot-workflow.
RequiredParameters:
  - edge-lab/reboot-workflow
Templates:
  - Name: "reboot-it"
    Path: ""
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}

      drpcli machines workflow $RS_UUID "" >/dev/null
      drpcli machines workflow $RS_UUID {{ .Param "edge-lab/reboot-workflow" }} >/dev/null

      # this is going to look like a reboot, fake a powercycle
      # MUST BE AFTER other machine updates or it will be over-written by next event
      if drpcli events post '{
        "Action": "powercycle",
        "Key": "{{ .Machine.Uuid }}",
        "Object": {{ .Machine | toJson }},
        "Principal": "runner:{{ .Machine.Uuid }}",
        "Type": "machines"
      }' > /dev/null; then
        echo "Sending Reboot Event (powercycle)"
        sleep 5
      else
        echo "Warning: failed trying to post Reboot Event (powercycle)"
      fi

      if [[ $(drpcli machines count Uuid Eq $RS_UUID Runnable Eq true) -eq 0 ]]; then
        echo "HALTED: operator marked machine not runnable during wait"
        exit 1
      fi

      echo "reboot exit code..."
      exit 192
Meta:
  icon: "recycle"
  color: "red"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
  copyright: "RackN 2019"
