---
Description: "A task to set RPi GPIO"
Name: "edge-lab-gpio"
Documentation: |
  If a SQUID LED is attached to the RPi, this will turn on different colors.
  It is very helpful for validating workflows during development

  You can supply an array with specific number of the GPIO pins to set.

  Three pin mappings to colors have been pre-wired:

  * 18 = red
  * 23 = green
  * 24 = blue

  See:
  https://github.com/simonmonk/squid
  https://www.raspberrypi.org/forums/viewtopic.php?f=5&t=5185#p68739
RequiredParameters:
  - edge-lab/gpio
Templates:
  - Name: "gpio"
    Path: ""
    Contents: |
      #!/usr/bin/env bash

      echo "enabling GPIO"
      sudo groupadd gpio
      sudo usermod -aG gpio root
      sudo chgrp gpio /sys/class/gpio/export
      sudo chmod 775 /sys/class/gpio/export
      sudo chgrp gpio /sys/class/gpio/unexport
      sudo chmod 775 /sys/class/gpio/unexport

      echo "Pin setting {{.Param "edge-lab/gpio" }}"
      {{ range $p, $v := .Param "edge-lab/gpio" }}

        pin={{$p}}
        if [[ "$pin" == "green" ]]; then pin=23; fi
        if [[ "$pin" == "blue" ]]; then pin=24; fi
        if [[ "$pin" == "red" ]]; then pin=18; fi

        echo "setting gpio${pin} ({{$p}}) to {{$v}}"
        echo "$pin" > /sys/class/gpio/export
        chmod -R 775 /sys/class/gpio/gpio${pin}
  
        echo "setting gpio${pin} to output 1"
        echo "out" > /sys/class/gpio/gpio${pin}/direction && true
        echo "{{$v}}" > /sys/class/gpio/gpio${pin}/value && true

      {{ else }}
        echo "no GPIO defined in edge-lab/gpio"
      {{ end }}

      echo "done"
      exit 0
Meta:
  icon: "lightbulb"
  color: "blue"
  title: "Community Content"
  copyright: "RackN 2021"
