---
Description: "A task to reboot to a workflow specifed by the edge-lab/reboot-workflow"
Name: "edge-lab-reboot-workflow"
Documentation: |
  A task to reboot to a workflow specifed by the edge-lab/reboot-workflow.
RequiredParameters:
  - edge-lab/reboot-workflow
Templates:
  - Name: "reboot-it"
    Path: ""
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}

      {{ if .ParamExists "edge-lab/reboot-workflow" }}
      drpcli machines meta set $RS_UUID key icon to "recycle"
      drpcli machines meta set $RS_UUID key color to "red"
      drpcli machines workflow $RS_UUID "" >/dev/null
      drpcli machines workflow $RS_UUID {{ .Param "edge-lab/reboot-workflow" }} >/dev/null
      {{ else }}
      echo "Missing parameter edge-lib/reboot-workflow"
      exit 1
      {{ end }}

      exit 192
Meta:
  icon: "recycle"
  color: "red"
  title: "Community Content"
  feature-flags: "sane-exit-codes"
  copyright: "RackN 2019"
