---
Name: flash-discover
Description: Detect which system firmware flash method to use.
Prerequisites:
  - hardware-tools-install
Templates:
  - Name: discover
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl"  .}}

      mfgr="$(drpcli gohai |jq -r '.DMI | .System | .Manufacturer')"
      {{ if ( .ParamExists "flash-manufacturer-override" ) -}}
      old="$mfgr"
      mfgr="{{ .Param "flash-manufacturer-override" }}"
      echo ">>> WARNING: 'flash-manufacturer-override' forced to '$mfgr'."
      echo "              Overriding discovered value of '$old'."
      {{ end -}}

      {{if eq (.Param "flash-method") "list" }}
      {{ if .ParamExists "flash-list" }}
      echo "Hardware system, $mfgr, updated by list. Assume list is self-contained."
      APPEND="-list"
      {{ else }}
      echo "List install requested, but list not specified!"
      exit 1
      {{ end }}
      {{end}}

      {{if eq (.Param "flash-method") "block" }}
      APPEND=""
      {{end}}

      {{if eq (.Param "flash-method") "list-then-block" }}
      APPEND=""
      {{ if .ParamExists "flash-list" }}
      echo "Hardware system, $mfgr, updated by list. Assume list is self-contained."
      APPEND="-list"
      {{ end }}
      {{end}}

      [[ -z "$mfgr" ]] && echo ">>> WARNING:  Discovered Manufacturer has no value." || true

      case $mfgr in
          "Dell Inc.") drpcli machines tasks add {{.Machine.UUID}} at 0 dell-firmware-flash${APPEND};;
          "HP"|"HPE") drpcli machines tasks add {{.Machine.UUID}} at 0 hpe-firmware-flash${APPEND};;
          Lenovo) drpcli machines tasks add {{.Machine.UUID}} at 0 lenovo-firmware-flash${APPEND};;
          *) echo "No idea how to flash${APPEND} for $mfgr";;
      esac
