---
Name: lenovo-firmware-flash-list
Description: Lenovo Flash From List
RequiredParams:
  - skip-flash
  - flash-list
Templates:
  - Name: prep-usb-nic
    Path: attach-usb-lan.sh
    ID: prep-usb-nic.sh.tmpl
  - Name: lenovo-firmware-flash-list
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}

      function clean_curl() {
          local _src=$1
          local _dest=$2

          echo "Downloading $_src"
          set +e
          curl -L -f -k -o $_dest $_src
          set -e
          if [[ $? != 0 ]] ; then
              xiterr 1 "Failed to download $_dest from $_src"
          fi
      }

      chmod +x attach-usb-lan.sh
      ./attach-usb-lan.sh

      skip_flash="{{.Param "skip-flash"}}"
      if [[ $skip_flash = true ]]; then
          echo "Skipping all flash operations due to skip-flash being true"
          exit 0
      fi

      if ! grep -q 'sledgehammer\.iso' /proc/cmdline; then
          echo "System not in Sledgehammer, exiting"
          exit 0
      fi

      [[ -d /sys/module/sg ]] || modprobe sg

      want_reboot=no
      failed=no
      {{ range $index, $elem := .Param "flash-list" }}
        {{ if not (has $elem.File ($.Param "flash-list-check-list")) }}
        FILENAME=$(basename "{{$elem.File}}")
        ID=$(basename $FILENAME .uxz)
        ID=$(basename $ID .bin)
        ID=$(basename $ID .tgz)
        DNAME=$(dirname "{{$elem.File}}")

        TMPDIR=$(mktemp -d "/tmp/flash-list-XXXXXXXX")

        {{ if $elem.Force }}
        FORCE="--forceid $ID"
        {{ else }}
        FORCE=
        {{ end }}
        {{ if $.Param "flash-list-force" }}
        FORCE="--forceid $ID"
        {{ end }}

        {{ if hasPrefix "http" $elem.File }}
        clean_curl "{{$elem.File}}" "$TMPDIR/$FILENAME"
        clean_curl "$DNAME/$ID.xml" "$TMPDIR/$ID.xml"
        {{ else }}
        clean_curl "{{$.ProvisionerURL}}/{{$elem.File}}" "$TMPDIR/$FILENAME"
        clean_curl "{{$.ProvisionerURL}}/$DNAME/$ID.xml" "$TMPDIR/$ID.xml"
        {{ end }}

        set +e
        /opt/OneCli/OneCli update flash --noreboot --scope individual --dir $TMPDIR --includeid ${ID} ${FORCE} --output flash.{{$index}}
        set -e

        lfailed=no
        this_one_reboot=false
        # Check for the presence of flash.{{$index}}/Onecli-update_flash_status.xml
        if [[ -e flash.{{$index}}/Onecli-update_flash_status.xml ]] ; then
          while read line; do
            case $line in
              *STATUS*)
                echo "STATUS line is $line"
                [[ $line = *'Package installed successfully'* ]] || [[ $line = *'Parse Firmware Package XML successfully'* ]] || lfailed=yes;;
              *REBOOT*)
                echo "REBOOT line is $line"
                [[ $lfailed = no && $line = *'Reboot Required'* ]] && this_one_reboot=yes
                [[ $lfailed = no && $line = *'reboot required'* ]] && this_one_reboot=yes
                [[ $lfailed = no && $line = *'Reboot is Required'* ]] && this_one_reboot=yes
                [[ $lfailed = no && $line = *'reboot is required'* ]] && this_one_reboot=yes
                [[ $lfailed = no && $line = *'No Reboot Required'* ]] && this_one_reboot=no
                [[ $lfailed = no && $line = *'No reboot required'* ]] && this_one_reboot=no
                [[ $lfailed = no && $line = *'no reboot required'* ]] && this_one_reboot=no;;
            esac
          done < <(awk '/<(REBOOT|STATUS)>/' flash.{{$index}}/Onecli-update_flash_status.xml |tac)
        else
          retco=0
          regex="<RETURNCODE>(.*)</RETURNCODE>"
          while read line; do
            case $line in
              *RETURNCODE*)
                if [[ "$line" =~ $regex ]] ; then
                  retco=${BASH_REMATCH[1]}
                fi;;
            esac
          done < <(awk '/<(RETURNCODE)>/' flash.{{$index}}/common_result.xml)

          case $retco in
            110)
              echo "Nothing to do - current level or no matching hardware";;
            *)
              echo "OneCli returned $retco"
              cat flash.{{$index}}/common_result.xml
              lfailed=yes;;
          esac
        fi

        if [[ "{{$elem.File}}" =~ xcc ]] ; then
            echo "Rebooting xcc"
            ipmitool mc reset cold
            # Wait for the reset to take effect.
            sleep 20
            set +e
            while true ; do
                ./attach-usb-lan.sh && /opt/OneCli/OneCli inventory getdevices && break
                echo "Not up yet"
                sleep 5
            done
            set -e
            echo "BMC is back up"
            sleep {{ .ParamExpand "flash-lenovo-xcc-reboot-wait" }}
        else
            if [[ $this_one_reboot = yes ]] ; then
                echo "Package {{$elem.File}} needs a reboot"
                echo "Want to reboot system"
                want_reboot=yes
            fi
        fi
        rm -rf $TMPDIR

        if [[ $lfailed = no ]] ; then
          drpcli machines get $RS_UUID param flash-list-check-list | jq ' (.+ ["{{$elem.File}}"] | unique)' | drpcli machines set $RS_UUID param flash-list-check-list to -
        fi
        if [[ $lfailed = yes ]] ; then
          failed=yes
        fi
        {{ else }}
        echo "Image {{$elem.File}} is already installed.  To reinstall, clear the 'flash-list-installed-list'"
        {{ end }}
      {{ end }}

      if [[ $want_reboot = yes ]]; then
          echo "Need reboot - start rebooting"
          exit_incomplete_reboot
      fi

      if [[ $failed = yes ]]; then
          echo "Something failed - error"
          exit 1
      fi

      {{ template "flash-list-installed.sh.tmpl" . }}

      echo "Nothing else to do and complete"
      drpcli machines set "$RS_UUID" param skip-flash to true
      exit 0
