---
Name: lenovo-firmware-flash
Description: Flash supported firmware on Lenovo systems
RequiredParams:
  - skip-flash
Templates:
  - Name: prep-usb-nic
    ID: prep-usb-nic.sh.tmpl
  - Name: acquire-latest-updates
    Contents: |
      #!/usr/bin/env bash
      [[ {{.Param "skip-flash"}} = true ]] && exit 0
      mt="$(drpcli gohai |jq -r '.DMI.Chassis| .[0]| .SKUNumber')"
      mt="${mt:0:4}"
      /opt/OneCli/OneCli update acquire --ostype platform --scope latest --mt "$mt"
  - Name: flash-latest-updates
    Contents: |
      #!/usr/bin/env bash
      [[ {{.Param "skip-flash"}} = true ]] && exit 0
      [[ -d /sys/module/sg ]] || modprobe sg
      /opt/OneCli/OneCli update flash --noreboot
      reboot=false
      fail=false
      while read line; do
          case $line in
             *STATUS*)
                 [[ $line = *'Package installed successfully'* ]] || fail=true;;
             *REBOOT*)
                 [[ $fail = false && $line = *'Reboot Required to take effect'* ]] && reboot=true;;
          esac
          [[ $reboot = true || $fail = true ]] && break
      done < <(awk '/<(REBOOT|STATUS)>/' logs/*/Onecli-update_flash_status.xml |tac)
      [[ $reboot = true ]] && exit 192
      [[ $fail = false ]]
