---
Description: "Return to using Runner Context"
Name: "context-runner"
Documentation: |
  Sets the Machine BaseContext to "runner", which returns it back to the fake
  machine runner when a Workflow is not being executed on a real Machine.

Templates:
  - Contents: |-
      #!/bin/bash
      # Set the Machine BaseContext to "runner"
      # RackN Copyright 2019

      set -e
      {{template "setup.tmpl" .}}

      # prepare machine for agent to take over
      drpcli machines meta set $RS_UUID key BaseContext to runner

      exit 0

    Name: "context-runner"
Meta:
  icon: "share"
  color: "black"
  title: "RackN"
  feature-flags: "sane-exit-codes"
