---
Description: "Build VSAN cluster."
Name: "esxi-vsan-build-cluster"
Documentation: |
  Build a VSAN cluster from previously configured VSAN hosts.
  Requires three VSAN hosts are defined in the Param ``esxi/vsan-members``.

  This workflow must be run on ONLY ONE of the VSAN members that were
  previously configured by ``esxi-vsan-configure-host`` task.

ExtraClaims:
  - scope: "machines"
    action: "*"
    specific: "*"
Meta:
  icon: "terminal"
  color: "purple"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
RequiredParams:
  - "esxi/vsan-members"
OptionalParams: []
Templates:
  - Name: "esxi-vsan-build-cluster.sh"
    Contents: |
      #!/usr/bin/env sh
      # Build the VSAN cluster from the hosts.

      ### setup.tmpl
      {{ template "setup.tmpl" . }}

      echo "This task has not been completed or tested.  Exiting with error."
      exit 1

      # incomplete
      #
      # LEADER
      # need to collect GOVC config for leader
      # run below - leader
      T=$(mktemp /tmp/vsan-cluster-get-$$-XXXXXXXX.txt)
      esxcli vsan cluster new
      esxcli vsan cluster get | tee $T
      ID=$(grep "Sub-Cluster UUID:" $T | awk ' { print $NF } ')
      drpcli machines set Name:{{ .Param "esxi/vsan-leader" }} param esxi/vsan-cluster-id to "$ID"


      # FOLLOWERS
      # wait for esxi/vsan-cluster-id to appear on the leader, then use it to join
      esxcli vsan cluster join -u $ID
