---
Description: "Gets detailed VSAN information and debug data of an ESXi host."
Name: "esxi-vsan-configure-host"
Documentation: |
  Configure VSAN on a vSphere ESXi host.

Meta:
  icon: "terminal"
  color: "purple"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
RequiredParams: []
OptionalParams: []
Templates:
  - Name: "esxi-vsan-configure-host.sh"
    Contents: |
      #!/usr/bin/env sh
      # Configure VSAN on an ESXi host via govc

      ### setup.tmpl
      {{ template "setup.tmpl" . }}

      ### govc-setup.sh.tmpl
      {{ template "govc-setup..sh.tmpl" . }}

      VSW='{{ .Param "esxi/vsan-vswitch-standard" }}'
      VMN='{{ .Param "esxi/vsan-vmnic" }}'
      PGR='{{ .Param "esxi/vsan-portgroup" }}'
      VMK='{{ .Param "esxi/vsan-vmk" }}'
      IP='{{ .Param "esxi/vsan-vmknic-ip" }}'
      NM='{{ .Param "esxi/vsan-vmknic-netmask" }}'

      # TODO: select Standard/Distributed vSwitch, check if exists, build if not
      #esxcli network vswitch standard add -v $VSW
      #esxcli network vswitch standard uplink add -v $VSW -u $VMN
      #esxcfg-vswitch -A $PGR $VSW

      #if [[ -z "$IP" && -z "$NM" ]]
      #then
      #  echo "esxi/vmknic-ip and netmask are both emptying, assuming existing configuration is correct"
      #else
      #  [[ -z "$IP" ]] && xiterr 1 "No value defined for 'esxi/vsan-vmknic-ip'"
      #  [[ -z "$NM" ]] && xiterr 1 "No value defined for 'esxi/vsan-vmknic-netmask'"
      #  esxcfg-vmknic -a -i $IP -n $NM -p $PGR
      #fi

      # verify vmkernel interface has vsan
      esxcfg-vmknic -l

      # adding a new interface:
      #esxcli vsan network ip add -i $VMK

      # changing existing interface to support VSAN
      esxcli vsan network ip set -i $VMK -T=vsan

