---
Name: "govc-stage-ova"
Description: "A task to stage the OVA inside the container Context"
Documentation: |
  This tasks stages the specified OVA in ``govc/ova-location`` Param inside
  the container Context.  Unfortunately, the _govc_ command does not appear
  to have support to specify remote resources as an HTTP/S URL reference.

  The OVA specified in the Param will be downloaded inside the container as
  a file named _import.ova_, which if that file exists, the ``govc-command``
  Task will append to the end of the executed _govc_ arguments.

RequiredParams:
  - "govc/ova-location"
OptionalParams: []
Templates:
  - Name: "govc-stage-ova.sh"
    Contents: |
      #!/usr/bin/env bash
      # Stage the OVA resource inside the container as 'import.ova'
      # RackN Copyright 2020

      set -e

      {{ template "setup.tmpl" .}}

      {{ if .ParamExists "govc/ova-location" }}
      which curl > /dev/null 2>&1 && { CMD="curl"; OPTS="-o"; }
      which wget > /dev/null 2>&1 && { CMD="wget"; OPTS="-O"; }
      mkdir -p /ova
      OVA='{{ .ParamExpand "govc/ova-location" }}'
      [[ -z "$OVA" ]] && xiterr 1 "No OVA supplied in 'govc/ova-location' param."
      if wget --spider "$OVA"
      then
        echo "OVA URL appears to be accessible"
      else
        xiterr 1 "URL test failed, unable to get OVA URL: '$OVA'"
      fi
      echo "Getting OVA: '$OVA'"
      $CMD $OPTS /ova/import.ova "$OVA"
      {{ else -}}
      xiterr 1 "'govc/ova-location' is required and was not specified"
      {{ end -}}

      echo "The OVA has been saved as '/ova/import.ova':"
      ls -lh /ova/import.ova

      exit 0
Meta:
  icon: "terminal"
  color: "blue"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
