---
Description: "A task to create Distributed Virtual Switches"
Name: "govc-dvs-create"
Documentation: |
  This task will create Distributed Virtual Switches in a vCenter service.
  It uses the ``esxi/dvs-mappings`` Param to define which DVSs and (optionally)
  portgroups to create, along with the configuration values for the DVS and
  Portgroups.

  Please review the Param documentation for ``esxi/dvs-mappings`` for structure
  and usage examples.

  In addition to ``esxi/dvs-mappings`` configuration values for each of the DVS
  and Portgroups, you must also add the ``esxi/dvs-memberships`` Param, which is
  an array of strings.  Each string should be the name of a Distributed Virtual
  Switch to create on the vSphere ESXi node.

  Typically the ``esxi/dvs-memberships`` Param will be added to a machine via
  classification rules.

Meta:
  icon: "terminal"
  color: "purple"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
RequiredParams:
  - "esxi/dvs-mappings"
  - "esxi/datacenter-name"
  - "esxi/cluster-name"
  - "govc/username"
  - "govc/password"
  - "govc/url"
OptionalParams:
  - "govc/debug"
ExtraClaims:
  - scope: "machines"
    action: "*"
    specific: "*"
Templates:
  - Name: "govc-dvs-create.sh"
    Contents: |
      #!/usr/bin/env bash
      # DVS create and enrollment task.
      # RackN Copyright 2020

      ### start setup.tmpl
      {{ template "setup.tmpl" . }}

      ### start govc-setup.sh.tmpl
      {{ template "govc-setup.sh.tmpl" . }}

      ### start govc-lib.sh.tmpl
      {{ template "govc-lib.sh.tmpl" . }}

      ### start govc-dvs-create.sh
      USERNAME="root"
      DC='{{ .Param "esxi/datacenter-name" }}'
      CLUSTER='{{ .Param "esxi/cluster-name" }}'
      [[ -z "$DC" ]] && xiterr 1 "'esxi/datacenter-name' not specified"

      export GOVC_PERSIST_SESSION=false
      export GOVC_DATACENTER="$DC"

      dvs_create() {
        [[ -z "$DC" ]] && xiterr 1 'DC name empty' || true
        [[ -z "$DVS_PATH" ]] && xiterr 1 'DVS Path empty' || true
        [[ -z "$DVS_MTU" ]] && xiterr 1 'DVS MTU empty' || true
        [[ -z "$DVS_VER" ]] && xiterr 1 'DVS Version empty' || true

        if [[ -z "$(run_govc quiet ls "$DVS_PATH")" ]]
        then
          run_govc dvs.create -dc "$DC" -product-version $DVS_VER -mtu $DVS_MTU -folder "$(dirname "$DVS_PATH")" "$(basename "$DVS_PATH")"
        else
          xiterr 1 "can not create DVS '$DVS_NAME' it exists already"
        fi
      }

      dvs_add() {
        [[ -z "$DC" ]] && xiterr 1 'Required DC name empty' || true
        [[ -z "$DVS_PATH" ]] && xiterr 1 'DVS Path empty' || true
        [[ -z "$DVS_VMN" ]] && xiterr 1 'Required DVS VMNIC device empty' || true
        [[ -z "$MEMBERS" ]] && xiterr 1 'Required Members to apply DVS to is empty' || true

        run_govc dvs.add -dvs "$DVS_PATH" -pnic $DVS_VMN $MEMBERS
      }

      portgroup_create() {
        local _vlan _ports
        [[ -z "$DC" ]] && xiterr 1 'Required DC name empty' || true
        [[ -z "$DVS_PATH" ]] && xiterr 1 'DVS path empty' || true
        [[ -z "$PG_NAME" ]] && xiterr 1 'Required Portgroup name empty' || true
        [[ -z "$PG_TYPE" ]] && xiterr 1 'Required Portgroup type empty' || true

        [[ "$PG_PORTS" == "0" || "$PG_PORTS" == "<no value>" || "$PG_PORTS" == "null" || -z "$PG_PORTS" ]] && _ports="" || _ports="-nports $PG_PORTS"
        [[ "$PG_VLAN" == "0" || "$PG_VLAN" == "<no value>" || "$PG_VLAN" == "null" || -z "$PG_VLAN" ]] && _vlan="" || _vlan="-vlan $PG_VLAN"

        local net_path="/$DC/network/$PG_NAME"

        if [[ -z "$(run_govc quiet ls "$net_path")" ]]
        then
          run_govc dvs.portgroup.add -dvs "$DVS_PATH" -type $PG_TYPE $_ports $_vlan "$PG_NAME"
        else
          xiterr 1 "can not create Portgroup '$PG_NAME' it exists already"
        fi
      }

      DC_PATH="/${DC}"
      if [[ -z "$(run_govc quiet ls "$DC_PATH")" ]]
      then
        xiterr 1 "Datacenter ('$DC') not created yet."
      fi

      echo "Starting DVS configuration based on 'esxi/dvs-mappings' Param."

      {{ range $dvs, $dvscfg := (.Param "esxi/dvs-mappings") -}}
      DVS_NAME="{{ $dvs }}"
      DVS_PATH="/${DC}/network/${DVS_NAME}"
      DVS_VER='{{$dvscfg.version}}'
      DVS_MTU='{{$dvscfg.mtu}}'
      DVS_DSC='{{$dvscfg.discovery}}'
      DVS_VMN='{{$dvscfg.vmnic}}'
      FOUND=""
      NAMES=""
      MEMBERS=""
      # now get our member nodes for this DVS

      echo ""
      echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ BEGIN DVS '$DVS_NAME' ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
      echo ""
      echo "Finding ESXi node members to operate on in cluster '$CLUSTER' with '$DVS_NAME' DVS."
      # DRP v4.5.0 release version will support the below Filter syntax for Params
      #NAMES=$(drpcli machines list esxi/cluster-name Eq "$CLUSTER" esxi/dvs-membershipos In "$DVS_NAME" Context Ne govc | jq -r ".[].Name" | tr '\n' ' ')
      # until then, selecting in JQ is our only path
      NAMES=$(drpcli machines list esxi/cluster-name Eq "$CLUSTER" Context Ne govc | jq -r ".[]  | select(.Params.\"esxi/dvs-memberships\" | index(\"$DVS_NAME\")) | .Name" | tr '\n' ' ')

      echo "Now convert found DRP Names to ESXi node names."
      echo "      DRP Names:  $NAMES"

      for NAME in $NAMES
      do
        MEMBERS="$(get_member_name $NAME) $MEMBERS"
      done
      [[ -n "$MEMBERS" ]] && FOUND="$MEMBERS" || FOUND="**NO HOSTS DEFINED**"
      echo "ESXi Node Names:  $FOUND"

      echo "Creating DVS '$DVS_NAME' with following configuration:"
      echo "============================================================================="
      echo "   esxi hosts:  $FOUND"
      echo "          mtu:  '$DVS_MTU'"
      echo "      version:  '$DVS_VER'"
      echo "    discovery:  '$DVS_DSC'"
      echo "        vmnic:  '$DVS_VMN'"

      dvs_create

      {{ if $dvscfg.portgroups -}}
      {{ range $pg, $pgcfg := $dvscfg.portgroups -}}
      PG_NAME='{{$pg}}'
      PG_TYPE='{{$pgcfg.type}}'
      PG_PORTS='{{$pgcfg.ports}}'
      PG_VLAN='{{$pgcfg.vlan}}'

      echo "Creating PortGroup '$PG_NAME' with the following configuration:"
      echo "============================================================================="
      echo "    portgroup: '$PG_NAME'"
      echo "         type: '$PG_TYPE'"
      echo "        ports: '$PG_PORTS'"
      echo "         vlan: '$PG_VLAN'"

      portgroup_create
      {{ else -}}
      echo "No Portgroups created as no configuration found for DVS '$DVS_NAME' on 'esxi/dvs-mappings' Param."
      {{ end -}}
      {{ end -}}

      echo "Adding members to DVS, if appropriate."
      [[ -n "$MEMBERS" ]] && dvs_add || echo "No ESXi members added, none tagged have '$DVS_NAME' via 'esxi/dvs-memberships' Param."

      {{ end -}}

      echo "End of DVS Creation from 'esxi/dvs-mappings' Param"
