---
Description: "A task wait for appliance OVA API to become available"
Name: "govc-cluster-create"
Documentation: |
  This task will create a cluster, file it in the ``govc/cluster-folder`` if
  provided, and enroll all Machines with the same cluster designation defined
  by the Param ``govc/cluster-name``.

ExtraClaims:
  - scope: "machines"
    action: "*"
    specific: "*"
Meta:
  icon: "terminal"
  color: "purple"
  title: "Digital Rebar Community Content"
  feature-flags: "sane-exit-codes"
RequiredParams:
  - "govc/cluster-name"
OptionalParams:
  - "govc/cluster-folder"
Templates:
  - Name: "govc-cluster-create.sh"
    Contents: |
      #!/bin/bash
      # Cluster create and enrollment task.
      # RackN Copyright 2020

      ###
      #  NOTICE:  This template relies on the 'govc/cluster-name' being set
      #           to a cluster name to operate on.  Additionally, each Machine
      #           that belongs in the specified cluster MUST ALSO have the
      #           Param set with the name of the clsuter.
      ###

      ### setup.tmpl
      {{ template "setup.tmpl" .}}

      ### govc-setup.sh.tmpl
      {{ template "govc-setup.sh.tmpl" .}}

      set -e

      JQ=$(which jq)
      [[ -z "$JQ" ]] && JQ=$(which drpjq)    || true
      [[ -z "$JQ" ]] && JQ=$(which drpclijq) || true
      [[ -z "$JQ" ]] && JQ=$(which gojq)     || true
      if [[ -z "$JQ" ]]; then
        D="$(which drpcli)"
        if [[ -n "$D" ]]; then
          ln -s $D /usr/local/bin/drpjq
          JQ="/usr/local/bin/drpjq"
        else
          xiterr 1 "Unable to find 'jq' or alternative to use."
        fi
      fi

      run_govc() {
        local _args="$*"
        echo "CMD: govc $_args"
        govc $_args
      }
      {{ $pass := "" }}
      {{ if .ParamExists "esxi/insecure-password" }}{{ $pass = ( .Param "esxi/insecure-password" ) }}{{ else }}{{ $pass = "RocketSkates"}}{{ end -}}
      USERNAME="root"
      DC='{{ .Param "govc/datacenter-name" }}'
      CLUSTER='{{ .Param "govc/cluster-name" }}'
      OPTIONS='{{ .Param "govc/cluster-options" }}'
      FOLDER='{{ .Param "govc/cluster-folder" }}'
      [[ -z "$CLUSTER" ]] && xiterr 1 "'govc/cluster-name' not specified"
      MEMBERS=$(drpcli machines list govc/cluster-name Eq "$CLUSTER" Meta.BaseContext Ne govc | jq -r '.[].Name' | tr '\n' ' ')

      echo "Starting create operation with the following information:"
      echo "---------------------------------------------------------"
      echo ""
      echo "     Datacenter:  '$DC'"
      echo "         Folder:  '$FOLDER'"
      echo "        Cluster:  '$CLUSTER'"
      echo "Cluster Options:  '$OPTIONS'"
      echo "        Members:  '$MEMBERS'"
      echo ""

      if [[ -n "$DC" ]]
      then
        if govc datacenter.info "$DC" > /dev/null 2>&1
        then
          echo "Datacenter '$DC' exists already."
        else
          run_govc datacenter.create "$DC"
        fi
      else
        echo "!!! NOTICE: 'govc/datacenter-name' not specified"
      fi

      export GOVC_DATACENTER="$DC"

      # This will need recursion to handle Folder path, since there appears
      # to be no option to create Parents automatically.
      if [[ -n "$FOLDER" ]]
      then
        if govc folder.info "$FOLDER" > /dev/null 2>&1
        then
          echo "Folder '$FOLDER' exists already."
        else
          run_govc folder.create "$FOLDER"
        fi
      else
        echo "No folder specified in 'govc/cluster-folder'."
      fi

      if [[ -n "$CLUSTER" ]]
      then
        # there appears to be no 'cluster.info' to test if exists - this is cheating but works
        if govc cluster.rule.info -cluster "$CLUSTER" > /dev/null 2>&1
        then
          echo "Cluster '$CLUSTER' exists already."
        else
          [[ -n "$FOLDER" ]] && FOLD="-folder=\"$FOLDER\""
          run_govc cluster.create $FOLD "$CLUSTER"
        fi

        if [[ -n "$OPTIONS" ]]
        then
          if govc cluster.rule.info -cluster "$CLUSTER" > /dev/null 2>&1
          then
            run_govc cluster.change $OPTIONS "$CLUSTER"
          else
            xiterr 1 "'govc/options' specified, but no 'govc/cluster-name' exists - failed create step?"
          fi
        else
          echo "No options specified in 'govc/cluster-options' to alter cluster with."
        fi

        # try to set based on Machien Name, FQDN, or fallback to IP Address
        # TODO:  This needs enhanced in conjunction with the govc context container
        #        to support DNS record checks in the future.
        get_member_name() {
          {{ if .ParamExists "govc/member-add-by-ip-address" }}
          echo $ADDR
          {{ else }}
          echo $MEMBER.$DNAME
          {{ end }}
        }

        cluster_add() {
          ADD_LOG=$(mktemp /tmp/cluster-add.$$.XXXXXXXX.log)
          echo ">>> Running cluster.add for '$MEMBER' with IP address '$ADDR'"
          echo ">>> 'cluster.add' running in the background, no live streaming of job log data."
          run_govc cluster.add -cluster "$CLUSTER" -hostname "$HNAME" -username "$USERNAME" -password '{{ $pass }}' $PRINT > $ADD_LOG
          echo ">>> 'cluster.add' operation for '$MEMBER' completed"
          echo ""
          echo ">>>>>>>>>>>>>>>>>>>>>>> START cluster.add log for '$MEMBER' <<<<<<<<<<<<<<<<<<<<<<<"
          cat $ADD_LOG
          echo ">>>>>>>>>>>>>>>>>>>>>>>> END cluster.add log for '$MEMBER' <<<<<<<<<<<<<<<<<<<<<<<<"
          echo ""
        }

        # now add Members to the cluster
        if [[ -n "$MEMBERS" ]]
        then
          # nuke all old logs, in case there are any left over from previous runs
          rm -f /tmp/cluster\.add*\.log
          for MEMBER in $MEMBERS
          do
            THUMB='{{ .Param "esxi/thumbprint-sha1" }}'
            DNAME=$(drpcli machines get Name:$MEMBER param dns-domain | jq -r '.')
            ADDR=$(drpcli machines show Name:$MEMBER --slim=Params,Meta | jq -r '.Address')
            [[ -n "$THUMB" ]] && PRINT="-thumbprint $THUMB" || PRINT="-noverify"

            HNAME=$(get_member_name)
            if [[ -n "$ADDR" ]]
            then
              cluster_add &
            else
              xiterr 1 "Unable to get '$MEMBER' IP Address."
            fi

            # reset our variables for next run cleanliness
            unset THUMB HNAME ADDR
          done

          # wait for all members to complete adding
          wait

          echo "All cluster member 'cluster.add' operations have completed."

        else
          echo "No members with 'govc/cluster-name' found to operate on."
        fi
      else
        echo "!!! NOTICE:  'govc/cluster-name' was not set, no cluster operations performed."
      fi

