---
Name: "flexiflow-stop"
Description: "Stop a flexiflow run"
Documentation: |
  This task ends the FlexiFLow stage.  No other tasks should follow it on
  the stage, and the only other task that should preceed is the ``flexiflow-start``
  task.

  Tasks will be dynamically injected in to the workflow if they have been specified
  by the appropriate control Params prior to this task.

Meta:
  color: "purple"
  icon: "magic"
  title: "RackN Content"
  feature-flags: "sane-exit-codes"
Templates:
- Name: "flexiflow_stop.sh"
  Contents: |
    #!/bin/bash
    # Copyright RackN, 2019

    echo "End of the FlexiFlow stage reached."
    exit 0
