---
Description: "Make sure that the EFI BootOrder variable has the NIC we installed from first."
Documentation: |
  Certian Linux distributions reorder the UEFI boot options to always
  locally boot from their install first, which is not generally what
  dr-provision wants, as it makes regaining control of the machine by
  PXE booting it to Sledgehammer harder.  This task rewrites the UEFI
  boot order to have whatever device we booted from be the first.
Name: always-pxe-in-uefi-first
Meta:
  type: "setup"
  title: Digital Rebar Community Content
  icon: "disk outline"
  color: "blue"
Templates:
  - Name: munge-boot-order-with-efibootmgr
    Contents: |
      #!/bin/bash
      {{ template "setup.tmpl" .}}
      set -x
      umount_things() {
          if [[ $efiVarsMounted ]]; then
              umount /sys/firmware/efi/efivars || :
          fi
          if [[ $sysMounted ]]; then
              umount /sys || :
          fi
      }
      trap umount_things EXIT
      if [[ ! -d /sys/firmware ]]; then
          mount -t sysfs sysfs /sys
          sysMounted=true
      fi
      if [[ ! -d /sys/firmware/efi ]]; then
          echo "No EFI firmware, nothing to do"
          exit 0
      fi
      if [[ $(echo /sys/firmware/efi/efivars/*) = '/sys/firmware/efi/efivars/*' ]]; then
          mkdir -p /sys/firmware/efi/efivars
          mount -t efivarfs efivarfs /sys/firmware/efi/efivars
          efiVarsMounted=true
      fi
      if ! which efibootmgr; then
          echo "Missing efibootmgr, please install it as part of your OS install"
          exit 1
      fi
      efibootmgr -v || :
      current="$(efibootmgr |awk '/^BootCurrent/ {print $2}')"
      order="$(efibootmgr |awk '/^BootOrder/ {print $2}')"
      if [[ ! $order ]]; then
          efibootmgr -o "$current"
      else
          IFS=',' read -r -a array <<< "$order"
          data="$(efibootmgr -D | grep -i NIC | awk '{ print $1 }' | awk -F\* '{ print $1 }' | sed 's/Boot//')"

          firstorder=""
          firstcomma=""
          lastorder=""
          lastcomma=""
          for elem in "${array[@]}"
          do
              FOUND=false
              while read NIC
              do
                  if [[ "$NIC" == "$elem" ]] ; then
                      FOUND=true
                      break
                  fi
              done < <(echo "$data")
              if [[ "$FOUND" == "true" ]] ; then
                  firstorder="${firstorder}${firstcomma}${elem}"
                  firstcomma=","
              else
                  lastorder="${lastorder}${lastcomma}${elem}"
                  lastcomma=","
              fi
          done
          order="${firstorder}${firstcomma}${lastorder}"

          echo "Setting order to $order"

          # remove the current from the front of order.
          efibootmgr -o "${order}"
      fi
      efibootmgr -D || :
      efibootmgr -v || :
