---
Name: "linux-selector"
Description: "Select the Linux bootenv to install"
Documentation: |

Meta:
  icon: "cloud"
  color: "yellow"
  title: "RackN Content"
Templates:
  - Name: "linux-selector.sh"
    ID: "linux-selector.sh.tmpl"