---
Name: set-machine-ip-in-joinup
Description: Read and Save the Machine IP
Documentation: /
  Alternative to set-machine-ip-in-sledgehammer.
  Used to read an existing IP address and assign it to the Machine

  This is needed when using the Join-Up process in clouds
  where no DHCP is used and machines are assigned fixed addresses.

  Needed in >v4.3 because IP setting was removed from join-up.sh
Templates:
  - Name: set-machine-ip
    Contents: |
      #!/usr/bin/env bash

      IP=""
      BOOTDEV="eth0"
      echo "Looking up IP address on $BOOTDEV"
      bootdev_ip4_re='inet ([0-9.]+)/([0-9]+)'
      bootdev_ip6_re='inet6 ([0-9a-fA-F:.]+)/([0-9]+) scope global'
      if [[ $(ip -4 -o addr show dev $BOOTDEV) =~ $bootdev_ip4_re ]]; then
          IP="${BASH_REMATCH[1]}"
      else
          if [[ $(ip -6 -o addr show dev $BOOTDEV) =~ $bootdev_ip6_re ]]; then
              IP="${BASH_REMATCH[1]}"
          fi
      fi

      echo "Address determined to be $IP"
      addr='{{.Machine.Address}}'
      [[ $IP && $addr != $IP ]] || exit 0
      echo "Address not set, updating"
      drpcli machines update "$RS_UUID" "{\"Address\":\"$IP\"}" &>/dev/null
      
      echo "done"
      exit 0
Meta:
  type: "config"
  icon: "magnet"
  color: "yellow"
  title: "Community Content"
  copyright: "RackN 2020"
  feature-flags: "sane-exit-codes"