---
Name: sledgehammer-set-working-python
Description: Sets the working python interpreter for future tasks.
Documentation: |
  Starting with the CentOS 8 version of Sledgehammer, there are
  two versions of Grub available -- python2 (2.7), and python3 (3.6).
  
  This task, in conjunction with the `spedgehammer/working-python`
  parameter, allows you to set which python is loaded when you use
  `/usr/bin/python`
Templates:
  - Name: set-working-python
    Contents: |
      #!/usr/bin/env bash
      if ! grep -q 'python - status is' < <(alternatives --display python); then
         echo "No python alternatives available"
         exit 0
      fi
      wanted='{{ .Param "sledgehammer/working-python" }}'
      case $wanted in
          auto) alternatives --auto python;;
          *) alternatives --set python $wanted;;
      esac
