---
Description: "Install k3s from Cluster Manager"
Name: "kube-lib-k3s-cluster"
Documentation: |
  This uses the v4.6+ cluster install pattern so it MUST be started
  from the cluster manager, not from one of the
  members of the cluster.

  If the cluster/filter does not match any machines then the task
  fail and allow operators to create the correct selectors.

  For operational guidelines, see :ref:`rs_cluster_pattern`
RequiredParams:
  - cluster/filter
  - cluster/manager
OptionalParams:
  - kube-lib/kube-config
ExtraClaims:
  - scope: "profiles"
    action: "*"
    specific: "*"
  - scope: "machines"
    action: "*"
    specific: "*"
Templates:
  - Name: "kube-lib-k3s-cluster-install.sh"
    Contents: |
      #!/usr/bin/env bash

      {{ template "setup.tmpl" . }}
      {{ template "cluster-utilities.tmpl" .}}

      echo "starting k3s leader install"
      cluster_wait_for_workflow_complete

      echo "--- install leader(s) for filter {{.Param "cluster/filter"}} --- "
      CLUSTER_LEADERS="$(drpcli machines list cluster/manager Eq false cluster/leader Eq true {{.Param "cluster/filter"}} --slim Params,Meta)"
      UUIDS=$(jq -rc ".[].Uuid" <<< "$CLUSTER_LEADERS")
      for uuid in $UUIDS; do
        echo "  starting k3s leader install workflow on $uuid"
        drpcli machines meta set $uuid key icon to anchor > /dev/null
        drpcli machines workflow $uuid k3s-machine-install > /dev/null
      done

      cluster_wait_for_workflow_complete

      echo "--- install workers for filter {{.Param "cluster/filter"}} --- "
      CLUSTER_WORKERS="$(drpcli machines list cluster/manager Eq false cluster/leader Eq false {{.Param "cluster/filter"}} --slim Params,Meta)"
      UUIDS=$(jq -rc ".[].Uuid" <<< "$CLUSTER_WORKERS")
      for uuid in $UUIDS; do
        echo "  starting k3s worker install workflow on $uuid"
        drpcli machines meta set $uuid key icon to ship > /dev/null
        drpcli machines workflow $uuid k3s-machine-install > /dev/null
      done

      echo "done (workers installs continue in parallel)"
      exit 0
Meta:
  type: "install"
  icon: "anchor"
  color: "brown"
  title: "Community Content"
  copyright: "RackN 2020"
  k3s: "true"
  feature-flags: "sane-exit-codes"
