---
Name: lab-drp-network
Description: Set up the DRP ip forwarding, masquerading, internal network, etc.
Documentation: |
  Set up DRP endpoint as an ip forwarding/masquerading gateway for the
  student lab machines.  Internal network is also set up, which the student
  virtual machines will be connected to, that the DRP endpoint provides the
  IP Forwarding services for.

  This is done using the cloud-inite per_once process.

Meta:
  color: blue
  feature-flags: sane-exit-codes
  icon: shopping cart
  title: RackN Content
OptionalParams: []
Prerequisites: []
Templates:
  - Contents: |-
      #!/usr/bin/env bash
      # Lab DRP network setup

      {{ template "setup.tmpl" .}}
      set -e

      EXT={{ .Param "lab-drp-external-network" }}
      INT={{ .Param "lab-drp-internal-network" }}
      PKGS="vim curl wget"

      echo "Setting up ip forwaarding ... "
      sysctl net.ipv4.ip_forward=1
      echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/50-ipv4_ip_forward.conf
      echo "Adding MASQUERADING rules for nat translation..."
      iptables -t nat -F
      iptables -t nat -A POSTROUTING -o $EXT -j MASQUERADE
      iptables-save > /etc/sysconfig/iptables
      chmod +x /etc/rc.d/rc.local
      echo "iptables -t nat -A POSTROUTING -o $EXT -j MASQUERADE" >> /etc/rc.d/rc.local

      echo "Configuring static network on internal $INT network..."
      #
      echo "
      DEVICE=$INT
      BOOTPROTO=none
      ONBOOT=yes
      PREFIX=24
      IPADDR=192.168.1.1
      " > /etc/sysconfig/network-scripts/ifcfg-$INT
      ifdown $INT || true
      ifup $INT

      echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      echo "nameserver 1.0.0.1" >> /etc/resolv.conf
      echo "nameserver 8.8.8.8" >> /etc/resolv.conf

      echo "{{ .ProvisionerAddress }}  drp" >> /etc/hosts

      [[ -n "$PKGS" ]] && yum -y install $PKGS

      rpm -q lldpd && { systemctl enable lldpd; systemctl start lldpd; } || echo "LLDPD not installed, not enabling"

    ID: ""
    Link: ""
    Meta: {}
    Name: "lab-drp-network"
    Path: ""
