---
Name: proxmox-create-storage
Description: "Create storage volumes for VM backing"
Documentation: |
  Create the ``local-lvm`` storage to an existing Proxmox VE server
  if it doesn't yet exist.

Meta:
  color: blue
  feature-flags: sane-exit-codes
  icon: expand arrows alternate
  title: RackN Content
OptionalParams: []
Prerequisites: []
Templates:
  - Name: "proxmox-create-storage"
    Contents: |-
      #!/usr/bin/env bash
      # Proxmox VE Storage create task

      ############### WARNING:
      ############### WARNING: THIS DESPERATELY need templatized !!!!
      ############### WARNING:

      function xiterr() { [[ $1 =~ ^[0-9]+$ ]] && { XIT=$1; shift; } || XIT=1; printf "FATAL: $*\n"; exit $XIT; }

      set -e

      PVENODE=$(hostname)
      DEVICE='{{ .Param "proxmox/storage-device" }}'
      NAME='{{ .Param "proxmox/storage-name" }}'
      VG="pve-vg-$NAME"

      if [[ ! -r "$DEVICE" ]]
      then
        echo "Unable to read requested storage device '$DEVICE'"
        echo "Found devices:"
        echo "--------------"
        lsblk
        xiterr 1 "Exiting with storage device selection error."
      else
        echo "Requested additional storage devices:  '$DEVICE'"
      fi

      #if pvesm list $NAME > /dev/null 2>&1
      if pvesm lvmthinscan $NAME > /dev/null 2>&1
      then
        echo "Storage volume named '$NAME' exists already.  Not doing anything."
        exit 0
      else
        echo "Storage volume named '$NAME' does not exist, will create it."
      fi

      set -x
      # ZAP the disk device - this needs safety guardrails - i.e. don't nuke root
      # if someone accitentally specifies it ... etc
      echo "Removing any potential existing LVM and disk vestiges"
      pvesm remove local-lvm || true
      lvremove -y $VG/$NAME || true
      vgremove -y $VG || true
      pvremove -y ${DEVICE}1 || true
      sgdisk -Z $DEVICE

      # initialize it with one partition
      sgdisk -N 1 $DEVICE
      # find our partition - NVMe drives tack on 'p1', while others just '1'
      PART=$(lsblk -npl "${DEVICE}" -o name,type | grep part | awk '{print $1}' | head -n1)

      # Create a Physical Volume (PV) without confirmation and 250K metadatasize
      pvcreate --metadatasize 250k -y -ff ${PART}

      # Create a volume group named “vmdata” on /dev/sdc1
      vgcreate $VG ${PART}

      # create a thin-pool Logical Volume (LV) named "vmdata" on VG "vmdata"
      lvcreate -l 95%FREE -n $NAME $VG
      lvconvert -y --type thin-pool $VG/$NAME

      # add the storage in to Proxmox CV as an LVM Thin type named "vmdata"
      pvesm add lvmthin $NAME -vgname $VG -thinpool $NAME -content rootdir,images -nodes $PVENODE
