---
Name: proxmox-debconf-set-selections
Description: ''
Documentation: ''
Meta:
  color: orange
  feature-flags: sane-exit-codes
  icon: expand arrows alternate
  title: RackN Content
RequiredParams: []
OptionalParams: []
Prerequisites: []
Templates:
  - Name: proxmox-debconf-set-selections
    Path: /root/proxmox-debconf-set-selections
    Contents: |
      samba-common    samba-common/do_debconf boolean true
      samba-common    samba-common/dhcp       boolean false
      samba-common    samba-common/workgroup  string  WORKGROUP
      postfix postfix/main_mailer_type        select  Local only
      postfix postfix/mailname        string  {{.Machine.Name}}
      postfix postfix/destinations    string  $myhostname, {{.Machine.Name}}, localhost.kvm-test.local, localhost

