---
Name: proxmox-drp-destroy-drp
Description: "Destroy the DRP VMs OS from the DRP installed on the Hypervisor"
Documentation: |
  Provisions the OS for the DRP VMs on the Proxmox host, via the DRP
  installed on the hypervisor.

Meta:
  color: blue
  feature-flags: sane-exit-codes
  icon: expand arrows alternate
  title: RackN Content
OptionalParams: []
Prerequisites: []
Templates:
  - Name: "proxmox-drp-provision-drp.tmpl"
    Contents: |-
      #!/usr/bin/env bash
      # Proxmox Lab setup virtual machines

      # BEGIN setup.tmpl
      {{ template "setup.tmpl" . }}

      # BEGIN proxmox-drp-provision-drp.tmpl
      {{ if eq ( .Param "proxmox/install-drp-on-hypervisor") true -}}
      echo "Attempting to DESTROY DRP on Hypervisor..."
      {{ else -}}
      echo "The 'proxmox/install-drp-on-hypervisor' Param is set to 'false'."
      echo "NOT attempting to DESTROY DRP ... exiting from the DRP destroy process."
      exit 0
      {{ end  -}}

      SCR=/usr/local/bin/drp-install.sh

      get_alt_script() {
        echo "$SCR wasn't found ... download alternate from 'get.rebar.digital/tip'"
        SCR=$(mktemp /tmp/install-script-XXXXXXX.sh)
        curl -s get.rebar.digital/tip > $SCR
        chmod 755 $SCR
        [[ ! -x "$SCR" ]] && xiterr 1 "No suitable script found to remove DRP..." || true
      }

      [[ -x "$SCR" ]] && echo "Using script '$SCR'..." || get_alt_script


      echo "Checking status of 'dr-provision' service..."
      systemctl status dr-provision > /dev/null 2>&1 || true
      STAT=$?

      if [[ $STAT -eq 0 ]]
      then
        echo "Stopping DRP service ..."
        systemctl stop dr-provision
        echo "Nuking DRP install on this system ..."
      elif [[ $STAT -eq 3 ]]
      then
        echo "DRP service found, but not running ... attempt to remove it ..."
      else
        echo "No DRP service found on host ($(hostname))."
        echo "Not exiting with an error."
        exit 0
      fi

      $SCR remove --remove-data
      systemctl daemon-reload
