---
Name: proxmox-debconf-set-selections
Description: ''
Documentation: |
  This task provides the Debian Package preset configuration input values
  needed to ensure automated installation of the samba and postfix packages.
  It also allows the operator to pre-seed and package configurations for
  any installed value.

  Set the ``proxmox/debconf-selections-template`` template to the name of
  your custom settings, which must conform to the debconf-set-selections
  structure.

  The template will be saved on the Machine under ``/root/proxmox-debconf-set-selections``
  and read in prior to package installation.

Meta:
  color: orange
  feature-flags: sane-exit-codes
  icon: expand arrows alternate
  title: RackN Content
RequiredParams: []
OptionalParams:
  - proxmox/debconf-selections-template
Prerequisites: []
Templates:
  - Name: proxmox-debconf-set-selections
    Contents: |
      #!/usr/bin/env bash
      # Get the debconf selections template and save it to /root/proxmox-debconf-set-selections

      {{ $tmpl := ( printf "%s" ( .Param "proxmox/debconf-selections-template") ) -}}

      cat << 'EOTMPL' > /root/proxmox-debconf-set-selections
      {{ .CallTemplate $tmpl . }}
      EOTMPL

