---
Name: dev-counter
Description: "Increment dev/counter"
Documentation: |
  When run, will add 1 to the dev/counter
OptionalParams:
  - dev/counter
Templates:
- Contents: |-
    #!/usr/bin/env bash

    set -e

    {{template "setup.tmpl" .}}

    echo "incrementing dev/counter.  new value is:"
    {{ if .ParamExists "dev/counter" }}
    drpcli machines set $RS_UUID param dev/counter to {{ add1 (.Param "dev/counter") }}
    {{ else }}
    drpcli machines add $RS_UUID param dev/counter to 1 
    {{ end }}

    echo "done"
    exit 0
  Name: dev-counter
Meta:
  title: "RackN Content"
  color: orange
  icon: "sort numeric up"
