---
Name: reboot-event
Description: "Send Reboot Event (dev testing)"
Documentation: |
  Handy for testing the UX, this task sends a powercycle event
Meta:
  title: "RackN Content"
  color: black
  feature-flags: sane-exit-codes
  icon: redo
Templates:
- Contents: |-
    #!/bin/bash
    # clear the workflow for a machine (makes it easy to rerun workflow)

    set -e

    {{template "setup.tmpl" .}}

    echo "Sending Reboot Event"

    drpcli events post '{
      "Action": "powercycle",
      "Key": "{{ .Machine.Uuid }}",
      "Object": {{ .Machine | toJson }},
      "Principal": "runner:{{ .Machine.Uuid }}",
      "Type": "machines"
    }' > /dev/null

    echo "now, wait for a little (two x dev/wait-time)"
    sleep {{ .Param "dev/wait-time" }}
    sleep {{ .Param "dev/wait-time" }}

    echo "Finished successfully"
    exit 0
  Name: reboot-event
